/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-container': '#eeeeee',
        'error-container': '#ffdad6',
        'primary-fixed': '#e2e2e2',
        'surface-container-highest': '#e2e2e2',
        'inverse-surface': '#2f3131',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#464747',
        'outline-variant': '#cfc4c5',
        'surface': '#f9f9f9',
        'on-secondary-container': '#5f6161',
        'on-surface-variant': '#4c4546',
        'secondary-container': '#dcdddd',
        'secondary-fixed-dim': '#c6c6c7',
        'tertiary': '#000000',
        'outline': '#7e7576',
        'surface-variant': '#e2e2e2',
        'on-error-container': '#93000a',
        'tertiary-container': '#1b1c1c',
        'on-background': '#1a1c1c',
        'surface-container-high': '#e8e8e8',
        'error': '#ba1a1a',
        'surface-container-low': '#f3f3f4',
        'surface-dim': '#dadada',
        'on-tertiary-container': '#848484',
        'on-primary-fixed-variant': '#474747',
        'on-error': '#ffffff',
        'inverse-primary': '#c6c6c6',
        'on-secondary': '#ffffff',
        'surface-tint': '#5e5e5e',
        'on-primary-fixed': '#1b1b1b',
        'on-primary-container': '#848484',
        'primary': '#000000',
        'primary-fixed-dim': '#c6c6c6',
        'tertiary-fixed-dim': '#c7c6c6',
        'secondary-fixed': '#e2e2e2',
        'secondary': '#5d5f5f',
        'primary-container': '#1b1b1b',
        'on-tertiary-fixed': '#1b1c1c',
        'on-surface': '#1a1c1c',
        'surface-bright': '#f9f9f9',
        'on-secondary-fixed': '#1a1c1c',
        'background': '#f9f9f9',
        'on-secondary-fixed-variant': '#454747',
        'inverse-on-surface': '#f0f1f1',
        'tertiary-fixed': '#e4e2e2',
      },
      fontFamily: {
        'display-lg': ['Playfair Display', 'serif'],
        'body-lg': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'label-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Montserrat', 'sans-serif'],
        'label-sm': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '4xl': '32px',
        '5xl': '40px',
        '6xl': '48px',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        'stack-md': '2rem',
        'margin-mobile': '20px',
        gutter: '24px',
        'stack-sm': '1rem',
        'stack-lg': '64px',
        'margin-desktop': '80px',
      },
      animation: {
        'bounce-slow': 'bounce-slow 4s ease-in-out infinite',
        'subtle-float': 'subtleFloat 5s ease-in-out infinite',
      },
      keyframes: {
        'bounce-slow': {
          '0%, 100%': { transform: 'translate(-50%, -55%)' },
          '50%': { transform: 'translate(-50%, -45%)' },
        },
        'subtleFloat': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
